import { theme } from 'antd'
import type { ThemeConfig } from 'antd'

export const lightTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,

    colorPrimary: '#01696F',
    colorPrimaryHover: '#0C4E54',
    colorPrimaryActive: '#094448',
    colorPrimaryBg: '#E6F4F4',
    colorPrimaryBgHover: '#D0ECEC',
    colorPrimaryBorder: '#A3D4D6',
    colorPrimaryBorderHover: '#6FBFC2',
    colorPrimaryText: '#01696F',
    colorPrimaryTextHover: '#0C4E54',

    colorBgBase: '#F7F6F2',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#F2F1ED',
    colorBgSpotlight: '#28251D',
    colorBgMask: 'rgba(40, 37, 29, 0.45)',

    colorText: '#28251D',
    colorTextSecondary: '#7A7974',
    colorTextTertiary: '#BAB9B4',
    colorTextQuaternary: '#D4D1CA',
    colorTextDisabled: '#BAB9B4',
    colorTextPlaceholder: '#BAB9B4',
    colorTextHeading: '#28251D',
    colorTextLabel: '#7A7974',
    colorTextDescription: '#7A7974',

    colorBorder: '#D4D1CA',
    colorBorderSecondary: '#E5E3DE',

    colorFill: '#F2F1ED',
    colorFillSecondary: '#F7F6F2',
    colorFillTertiary: '#FAFAF8',
    colorFillQuaternary: '#FCFCFB',

    colorError: '#C0392B',
    colorErrorBg: '#FDECEA',
    colorErrorBorder: '#F5A29A',
    colorErrorHover: '#E85B4D',
    colorErrorText: '#C0392B',
    colorWarning: '#B7560E',
    colorWarningBg: '#FDF3E7',
    colorWarningBorder: '#F5C48A',
    colorWarningText: '#B7560E',
    colorSuccess: '#2E7D32',
    colorSuccessBg: '#EAF4EA',
    colorSuccessBorder: '#95CF97',
    colorSuccessText: '#2E7D32',
    colorInfo: '#01696F',
    colorInfoBg: '#E6F4F4',
    colorInfoBorder: '#A3D4D6',
    colorInfoText: '#01696F',

    borderRadius: 10,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    borderRadiusXS: 4,

    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    paddingXS: 8,
    paddingXXS: 4,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    marginXS: 8,
    marginXXS: 4,

    boxShadow: '0 1px 2px rgba(40, 37, 29, 0.06), 0 8px 24px rgba(40, 37, 29, 0.08)',
    boxShadowSecondary: '0 10px 30px rgba(40, 37, 29, 0.10)',

    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    motionEaseInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',

    lineHeight: 1.6,
    lineHeightLG: 1.6,
    lineHeightSM: 1.5,

    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
  },
  components: {
    Layout: {
      siderBg: '#FFFFFF',
      headerBg: '#FFFFFF',
      bodyBg: '#F2F1ED',
      triggerBg: '#F7F6F2',
      triggerColor: '#7A7974',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#E6F4F4',
      itemSelectedColor: '#01696F',
      itemHoverBg: '#F2F1ED',
      itemHoverColor: '#28251D',
      itemColor: '#7A7974',
      itemActiveBg: '#E6F4F4',
      subMenuItemBg: 'transparent',
      iconSize: 16,
      collapsedIconSize: 18,
    },
    Table: {
      headerBg: '#E6F4F4',
      headerColor: '#7A7974',
      headerSortActiveBg: '#F2F1ED',
      rowHoverBg: '#F7F6F2',
      borderColor: '#E5E3DE',
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
    },
    Card: {
      paddingLG: 24,
      headerBg: 'transparent',
      actionsLiMargin: '12px 0',
      boxShadow: '0 1px 2px rgba(40, 37, 29, 0.06), 0 10px 26px rgba(40, 37, 29, 0.08)',
    },
    Button: {
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Input: {
      activeBorderColor: '#01696F',
      hoverBorderColor: '#0C4E54',
    },
    Select: {
      optionSelectedBg: '#E6F4F4',
      optionSelectedColor: '#01696F',
    },
    Tabs: {
      inkBarColor: '#01696F',
      itemSelectedColor: '#01696F',
      itemHoverColor: '#0C4E54',
      itemColor: '#7A7974',
    },
    Tag: {
      defaultBg: '#F2F1ED',
      defaultColor: '#7A7974',
    },
    Drawer: {
      colorBgElevated: '#FFFFFF',
    },
    Tooltip: {
      colorBgSpotlight: '#28251D',
      colorTextLightSolid: '#FFFFFF',
    },
    Badge: {
      colorBgContainer: '#FFFFFF',
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize: 13,
    },
  },
}

export const darkTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,

    colorPrimary: '#4F98A3',
    colorPrimaryHover: '#6BB3BD',
    colorPrimaryActive: '#3D8591',
    colorPrimaryBg: '#0E2527',
    colorPrimaryBgHover: '#122E31',
    colorPrimaryBorder: '#1E4E54',
    colorPrimaryBorderHover: '#2E6E75',
    colorPrimaryText: '#4F98A3',
    colorPrimaryTextHover: '#6BB3BD',

    colorBgBase: '#141312',
    colorBgContainer: '#1C1B19',
    colorBgElevated: '#242320',
    colorBgLayout: '#141312',
    colorBgSpotlight: '#CDCCCA',
    colorBgMask: 'rgba(0, 0, 0, 0.60)',

    colorText: '#CDCCCA',
    colorTextSecondary: '#8A8987',
    colorTextTertiary: '#5C5B59',
    colorTextQuaternary: '#3A3937',
    colorTextDisabled: '#5C5B59',
    colorTextPlaceholder: '#5C5B59',
    colorTextHeading: '#CDCCCA',
    colorTextLabel: '#8A8987',
    colorTextDescription: '#8A8987',

    colorBorder: '#3A3937',
    colorBorderSecondary: '#2E2D2B',

    colorFill: '#242320',
    colorFillSecondary: '#1C1B19',
    colorFillTertiary: '#181716',
    colorFillQuaternary: '#161514',

    colorError: '#F17B72',
    colorErrorBg: '#2D1614',
    colorErrorBorder: '#7A3A36',
    colorErrorHover: '#F5948D',
    colorErrorText: '#F17B72',
    colorWarning: '#E0924A',
    colorWarningBg: '#2B1D10',
    colorWarningBorder: '#6A3E1A',
    colorWarningText: '#E0924A',
    colorSuccess: '#68BB6E',
    colorSuccessBg: '#0E2110',
    colorSuccessBorder: '#2A5C2D',
    colorSuccessText: '#68BB6E',
    colorInfo: '#4F98A3',
    colorInfoBg: '#0E2527',
    colorInfoBorder: '#1E4E54',
    colorInfoText: '#4F98A3',

    borderRadius: 10,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    borderRadiusXS: 4,

    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    paddingXS: 8,
    paddingXXS: 4,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    marginXS: 8,
    marginXXS: 4,

    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.35), 0 12px 28px rgba(0, 0, 0, 0.45)',
    boxShadowSecondary: '0 16px 40px rgba(0, 0, 0, 0.50)',

    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    motionEaseInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',

    lineHeight: 1.6,
    lineHeightLG: 1.6,
    lineHeightSM: 1.5,

    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
  },
  components: {
    Layout: {
      siderBg: '#1C1B19',
      headerBg: '#1C1B19',
      bodyBg: '#141312',
      triggerBg: '#242320',
      triggerColor: '#8A8987',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#0E2527',
      itemSelectedColor: '#4F98A3',
      itemHoverBg: '#242320',
      itemHoverColor: '#CDCCCA',
      itemColor: '#8A8987',
      itemActiveBg: '#0E2527',
      subMenuItemBg: 'transparent',
      iconSize: 16,
      collapsedIconSize: 18,
    },
    Table: {
      headerBg: '#0E2527',
      headerColor: '#8A8987',
      headerSortActiveBg: '#122E31',
      rowHoverBg: '#1F1E1C',
      borderColor: '#2E2D2B',
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
    },
    Card: {
      paddingLG: 24,
      headerBg: 'transparent',
      boxShadow: '0 1px 2px rgba(0, 0, 0, 0.35), 0 14px 30px rgba(0, 0, 0, 0.45)',
    },
    Button: {
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Input: {
      activeBorderColor: '#4F98A3',
      hoverBorderColor: '#6BB3BD',
    },
    Select: {
      optionSelectedBg: '#0E2527',
      optionSelectedColor: '#4F98A3',
    },
    Tabs: {
      inkBarColor: '#4F98A3',
      itemSelectedColor: '#4F98A3',
      itemHoverColor: '#6BB3BD',
      itemColor: '#8A8987',
    },
    Tag: {
      defaultBg: '#242320',
      defaultColor: '#8A8987',
    },
    Drawer: {
      colorBgElevated: '#1C1B19',
    },
    Message: {
      contentBg: '#242320',
    },
    Notification: {
      colorSuccessBg: '#0E2110',
      colorErrorBg: '#2D1614',
      colorInfoBg: '#0E2527',
      colorWarningBg: '#2B1D10',
    },
    Tooltip: {
      colorBgSpotlight: '#2A2927',
      colorTextLightSolid: '#CDCCCA',
    },
    Badge: {
      colorBgContainer: '#1C1B19',
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize: 13,
    },
  },
}
